
services:

  redis-signle:
    image: redis:7.0
    container_name: redis-signle
    ports:
      - "6390:6379"

  redis-1:
    image: redis:7.0
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 32M
        reservations:
          cpus: '0.1'
          memory: 32M
    container_name: redis-master
    command: redis-server --appendonly yes --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000
    ports:
      - "6379:6379"
    networks:
      - yt-net

  redis-2:
    image: redis:7.0
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 32M
        reservations:
          cpus: '0.1'
          memory: 32M
    container_name: redis-2
    command: redis-server --appendonly yes --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000
    ports:
      - "7002:6379"
    networks:
      - yt-net

  redis-3:
    image: redis:7.0
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 128M
        reservations:
          cpus: '0.1'
          memory: 128M
    container_name: redis-3
    command: redis-server --appendonly yes --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000
    ports:
      - "7003:6379"
    networks:
      - yt-net

  # redis-4:
  #   image: redis:7.0
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '0.1'
  #         memory: 32M
  #       reservations:
  #         cpus: '0.1'
  #         memory: 32M
  #   container_name: redis-4
  #   command: redis-server --appendonly yes --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000
  #   ports:
  #     - "7004:6379"
  #   networks:
  #     - yt-net

  # redis-5:
  #   image: redis:7.0
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '0.1'
  #         memory: 128M
  #       reservations:
  #         cpus: '0.1'
  #         memory: 128M
  #   container_name: redis-5
  #   command: redis-server --appendonly yes --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000
  #   ports:
  #     - "7005:6379"
  #   networks:
  #     - yt-net

  # redis-6:
  #   image: redis:7.0
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '0.1'
  #         memory: 32M
  #       reservations:
  #         cpus: '0.1'
  #         memory: 32M
  #   container_name: redis-6
  #   command: redis-server --appendonly yes --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000
  #   ports:
  #     - "7006:6379"
  #   networks:
  #     - yt-net

  redis-cluster-creator:
    image: redis:7.0
    container_name: redis-cluster-creator
    depends_on:
      - redis-1
      - redis-2
      - redis-3
      # - redis-4
      # - redis-5
      # - redis-6
    # command: bash -c "sleep 5 && redis-cli --cluster create redis-master:6379 redis-2:6379 redis-3:6379 redis-4:6379 redis-5:6379 redis-6:6379 --cluster-replicas 1 --cluster-yes"
    command: bash -c "sleep 5 && redis-cli --cluster create redis-master:6379 redis-2:6379 redis-3:6379 --cluster-replicas 0 --cluster-yes"
    networks:
      - yt-net

networks:
  yt-net:
    driver: bridge
